# Generated by Django 3.2.3 on 2022-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=320, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('languages', models.JSONField(null=True)),
                ('download_count', models.IntegerField(null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
